import time

import streamlit as st
from sentence_transformers import SentenceTransformer

from src.config import EMBEDDING_MODEL
from src.retriever import get_or_create_collection, semantic_search, UserConstraints, build_query_text
from src.reranker import rerank, RankedResult
from src.data_pipeline import load_cache
from src.llm_generator import generate_baseline_plan_groq, generate_meal_plan_groq, extract_ingredients_from_image
from src.recipe_processor import load_recipes, load_cleaned_recipes, build_chroma_index

st.set_page_config(page_title="MacroMind", page_icon="🥗", layout="wide")


@st.cache_resource
def load_model():
    return SentenceTransformer(EMBEDDING_MODEL)


@st.cache_resource
def load_collection():
    _, collection = get_or_create_collection()
    return collection


def run_pipeline(constraints: UserConstraints, variant: str, api_key: str) -> dict:
    result = {"response_text": "", "candidates": [], "ranked": [], "latency": 0.0, "error": None}
    t0 = time.time()
    try:
        model = load_model()
        collection = load_collection()

        if variant == "baseline":
            result["response_text"] = generate_baseline_plan_groq(constraints, api_key)

        elif variant == "rag":
            query = build_query_text(constraints)
            search_results = semantic_search(query, collection, model, n_results=5)
            result["candidates"] = search_results
            result["ranked"] = [
                RankedResult(r.recipe_id, r.name, 1 - r.score, 0.0, 0.0, 0.0, r.metadata)
                for r in search_results
            ]
            result["response_text"] = generate_meal_plan_groq(constraints, result["ranked"], api_key)

        elif variant == "rag-rerank":
            query = build_query_text(constraints)
            search_results = semantic_search(query, collection, model, n_results=20)
            result["candidates"] = search_results
            result["ranked"] = rerank(search_results, constraints, top_k=5)
            result["response_text"] = generate_meal_plan_groq(
                constraints, result["ranked"], api_key, use_rerank_prompt=True
            )

    except Exception as e:
        result["error"] = str(e)
    result["latency"] = round(time.time() - t0, 2)
    return result


# ── Sidebar ────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.title("MacroMind")
    st.caption("Constraint-aware meal planning with RAG")

    variant = st.selectbox(
        "Variant",
        options=["baseline", "rag", "rag-rerank"],
        format_func=lambda v: {"baseline": "V1 Baseline", "rag": "V2 RAG", "rag-rerank": "V3 RAG + Rerank"}[v],
    )

    api_key = st.text_input("Groq API Key", type="password", help="Free at console.groq.com")

    st.divider()

    if st.button("Rebuild Index (both sources)"):
        with st.spinner("Indexing ~10k recipes…"):
            model = load_model()
            _, col = get_or_create_collection()
            nutrition_cache = load_cache()
            recipes = list({r.id: r for r in load_recipes() + load_cleaned_recipes()}.values())
            build_chroma_index(recipes, col, model, nutrition_cache)
        st.success(f"Done. {col.count()} recipes indexed.")

    st.divider()
    with st.expander("⚠️ Corpus limitations"):
        st.caption(
            "RecipeNLG is sourced from English-language cooking websites — Western and American "
            "cuisine is overrepresented. South Asian, West African, East Asian, Latin American, "
            "and Middle Eastern food traditions are largely absent. TheMealDB adds ~300 globally "
            "diverse recipes. Pricing uses US grocery estimates. Macro values for RecipeNLG recipes "
            "are estimated from 100 g-per-ingredient defaults, not verified weights. "
            "Do not use for clinical dietary planning."
        )

# ── Consent gate ──────────────────────────────────────────────────────────────

if not st.session_state.get("consent"):
    st.title("MacroMind — Meal Planner")
    st.markdown("---")
    st.subheader("Before you continue, please read the following")
    st.markdown(
        """
**MacroMind is an educational tool, not a medical service.**

- Meal plans and macro estimates are generated by AI models and are **approximations only**. They have not been reviewed by a dietitian, nutritionist, or physician.
- Calorie, protein, fat, and carbohydrate values are computed from ingredient-level estimates and may differ significantly from actual nutritional content.
- Cost estimates are based on US grocery averages and may not reflect your local prices.
- **If you have a medical condition, eating disorder, food allergy, or are pregnant or breastfeeding**, do not follow AI-generated diet plans without consulting a registered dietitian or your healthcare provider.
- **If you are struggling with food or your relationship with eating**, please reach out to the National Eating Disorders Association (NEDA) helpline: **1-800-931-2237** (call or text) or visit nationaleatingdisorders.org.
- This app is intended for educational and research purposes only.
        """
    )
    st.markdown("---")
    if st.button("I understand — take me to the planner", type="primary"):
        st.session_state.consent = True
        st.rerun()
    st.stop()

# ── Main form ──────────────────────────────────────────────────────────────────

st.header("Meal Planner")

# Voice input lives outside the form so transcription triggers reactively
if api_key:
    audio_value = st.audio_input("🎤 Or speak your pantry ingredients")
    if audio_value is not None:
        try:
            from groq import Groq as _Groq
            _client = _Groq(api_key=api_key)
            _transcript = _client.audio.transcriptions.create(
                model="whisper-large-v3-turbo",
                file=("pantry.wav", audio_value.getvalue(), "audio/wav"),
                prompt="List of food ingredients, comma separated.",
            )
            st.session_state.pantry_raw = _transcript.text
            st.success(f"Transcribed: {_transcript.text}")
        except Exception as _e:
            st.warning(f"Voice transcription failed: {_e}")
else:
    st.caption("Voice input requires a Groq API key (enter it in the sidebar).")

import os as _os
_google_api_key = _os.getenv("GOOGLE_API_KEY", "")
if _google_api_key:
    uploaded_image = st.file_uploader(
        "📷 Or upload a fridge/pantry photo",
        type=["jpg", "jpeg", "png"],
        help="MacroMind will detect ingredients from the image using Gemini vision.",
    )
    if uploaded_image is not None:
        try:
            _img_bytes = uploaded_image.read()
            _detected = extract_ingredients_from_image(_img_bytes, _google_api_key)
            st.session_state.pantry_raw = _detected
            st.success(f"Detected ingredients: {_detected}")
        except Exception as _e:
            st.warning(f"Image ingredient detection failed: {_e}")
else:
    st.caption("Image pantry detection requires a Google API key (set GOOGLE_API_KEY in .env).")

with st.form("meal_plan_form"):
    col1, col2 = st.columns(2)
    with col1:
        calories = st.number_input("Calories (kcal)", min_value=500, max_value=5000, value=2000, step=50)
        protein_g = st.number_input("Protein (g)", min_value=0, max_value=400, value=120, step=5)
    with col2:
        carbs_g = st.number_input("Carbs (g)", min_value=0, max_value=600, value=200, step=10)
        fat_g = st.number_input("Fat (g)", min_value=0, max_value=300, value=65, step=5)

    use_budget = st.checkbox("Set daily budget", value=False)
    budget_usd = st.number_input("Budget (USD/day)", min_value=1.0, max_value=50.0, value=12.0, step=0.5) if use_budget else 999.0

    dietary_tags = st.multiselect(
        "Dietary restrictions",
        options=["vegetarian", "vegan", "gluten-free", "keto"],
        default=[],
    )

    allergy_tags = st.multiselect(
        "Allergen restrictions (FDA Big-9)",
        options=["tree nuts", "peanuts", "dairy", "eggs", "shellfish", "fish", "soy", "wheat/gluten", "sesame"],
        default=[],
    )

    cultural_dietary = st.multiselect(
        "Cultural / religious dietary requirements",
        options=["halal", "kosher", "jain", "hindu vegetarian (no beef)", "buddhist (no meat)"],
        default=[],
    )
    if cultural_dietary:
        st.caption(
            "Cultural and religious dietary filters use ingredient-level heuristics and cannot "
            "guarantee full compliance with religious law. Verify with your religious authority "
            "or a certified halal/kosher supplier."
        )

    pantry_raw = st.text_area(
        "Pantry ingredients (comma-separated)",
        placeholder="chicken, rice, broccoli, eggs",
        key="pantry_raw",
    )
    available_ingredients = [i.strip() for i in pantry_raw.split(",") if i.strip()] if pantry_raw else []

    submitted = st.form_submit_button("Generate Meal Plan", type="primary")

# ── Results ────────────────────────────────────────────────────────────────────

if submitted:
    if not api_key:
        st.error("Enter a Groq API key in the sidebar to generate a plan.")
    else:
        if calories < 800:
            st.error(
                "This calorie target is below safe minimums. MacroMind cannot generate a plan at this level. "
                "If you are struggling with food, please contact the **NEDA helpline: 1-800-931-2237** "
                "(call or text) or visit nationaleatingdisorders.org."
            )
            st.stop()
        elif calories < 1200:
            st.warning(
                "⚠️ This target is below the typical minimum for adults (1,200 kcal/day). "
                "Consult a registered dietitian before following a plan at this level."
            )

        if allergy_tags:
            st.warning(
                "⚠️ Allergen filtering is based on ingredient names in the corpus and may not "
                "catch all sources of an allergen. Always read labels and verify with a healthcare provider."
            )

        constraints = UserConstraints(
            calories=float(calories),
            protein_g=float(protein_g),
            carbs_g=float(carbs_g),
            fat_g=float(fat_g),
            budget_usd=float(budget_usd),
            available_ingredients=available_ingredients,
            dietary_tags=dietary_tags,
            allergy_tags=allergy_tags,
            cultural_dietary=cultural_dietary,
        )

        with st.spinner("Generating meal plan…"):
            output = run_pipeline(constraints, variant, api_key)

        if output["error"]:
            st.error(f"Error: {output['error']}")
        else:
            variant_label = {"baseline": "V1 Baseline", "rag": "V2 RAG", "rag-rerank": "V3 RAG + Rerank"}[variant]
            m1, m2, m3 = st.columns(3)
            m1.metric("Variant", variant_label)
            m2.metric("Latency", f"{output['latency']}s")
            m3.metric("Recipes retrieved", len(output["candidates"]) or "n/a")

            st.markdown("### Meal Plan")
            st.markdown(output["response_text"])

            if output["ranked"]:
                st.markdown("### Retrieved Recipes")
                for r in output["ranked"]:
                    meta = r.metadata
                    with st.expander(f"{r.name}  (score: {r.score:.3f})"):
                        cols = st.columns(4)
                        cols[0].metric("Calories", f"{meta.get('calories', '?')} kcal")
                        cols[1].metric("Protein", f"{meta.get('protein', '?')}g")
                        cols[2].metric("Carbs", f"{meta.get('carbs', '?')}g")
                        cols[3].metric("Cost", f"${meta.get('cost_usd', '?')}")
                        if meta.get("tags"):
                            st.caption(f"Tags: {meta['tags'].replace('|', ' · ')}")
